### ISSUE TITLE
Ontology completed

### ISSUE THREAD

**Issue by ashepherd** [oceanproteinportal/ontology#3]
@jaclynsaunders, I completed the ontology, and updated the conceptual modeling diagrams with a new ontology owl file. I added one new class in between the ProteinIdentification and the Sample. This was so that as the spectral counts for a protein from each sample changes, we don't have to duplicate the identifying info for each sample. we store the protein ID info once, then just point to it from each protein spectral count value. Let me know if that is correct?

This is diagrammed here: 
https://github.com/oceanproteinportal/ontology/blob/main/conceptual-model/OPP%20Ontology%20-%20Identification%20of%20AminoAcids.png

**Comment by jaclynsaunders** [comment]
Aha. I think I understand. Absolute Unites & Peak Area would need to be treated similarly to the spectral counts then as well. (The probability will potentially change from sample to sample as well, depending on the dataset.)

**Comment by ashepherd** [comment]
Ah right. Thanks! Anything on the peptide side that would act similarly?

**Comment by jaclynsaunders** [comment]
Yeah. The following would also vary by sample:

- Absolute units
- Plus234HSpectraCount
- SpectralCountSum
- medianRetentionTime (these will be roughly similar, but might vary slightly)
- totalTIC
- peakArea
- SEQUEST scores may vary slightly from sample to sample as well


Also, if we have PTMs, then the peptide sequence alone is not unique. {Peptide + PTM} is unique. Unless we choose to aggregate the PTMs (and non-PTM) into one. How to handle that should be based off of how difficult it is to have the set of {Peptide + PTM} as the unique vs just peptide along with Mak’s input about integrating PTM’s. I’m meeting with him on Monday and can ask.
