### ISSUE TITLE
Link identifiers.org to the NamedIndividuals of the ProteinIdentifierScheme

### ISSUE THREAD

**Issue by ashepherd** [oceanproteinportal/ontology#5]
PFam: https://registry.identifiers.org/registry/pfam
Uniprot: https://registry.identifiers.org/registry/uniprot
Kegg: https://registry.identifiers.org/registry/kegg
NCBI: https://registry.identifiers.org/registry/ncbiprotein

=== NOT IN IDENTIFIERS.ORG ===
EC: http://www.wikidata.org/entity/Q741108

**Comment by jaclynsaunders** [comment]
Do you think we should be linking to these for BCODMONT? Currently, we are using different IRIs EDAM (http://edamontology.org/data_1138 etc.) This part of the ontology hasn't been compiled yet, so would be a quick change. Thanks!
