### ISSUE TITLE
Do we need to add `keggPathwayIndex` to the ontology?

### ISSUE THREAD

**Issue by ashepherd** [oceanproteinportal/ontology#7]

**Comment by jaclynsaunders** [comment]
What's an example of the data in this field? (I don't see a direct field for that displayed on the current site.) Thanks!

**Comment by ashepherd** [comment]
I didn't see one either, so i must've been getting all philosophical here. :) ok to remove it?

**Comment by jaclynsaunders** [comment]
If the data looks similar to a pattern like "ko00920" then keep it, otherwise probably safe to remove.
